Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "centos7-vm"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/install_docker.yml"
    ansible.verbose = true 
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/build_sqlite.yml"
    ansible.verbose = true
  end
end
